In [15]:
import pandas as pd
pd.options.display.max_columns = None
pd.options.display.max_rows = 50
import re

# Data cleaning

In [24]:
file_path = 'Quality_of_Life_Index.csv'
data = pd.read_csv(file_path)

In [25]:
data.City[:50]

0     The Hague (Den Haag), Netherlands
1                Luxembourg, Luxembourg
2                Eindhoven, Netherlands
3                Rotterdam, Netherlands
4                   Zurich, Switzerland
5                   Copenhagen, Denmark
6                       Vienna, Austria
7                     Helsinki, Finland
8                   Geneva, Switzerland
9                    Frankfurt, Germany
10                   Stuttgart, Germany
11               Amsterdam, Netherlands
12                   Reykjavik, Iceland
13                     Perth, Australia
14            Austin, TX, United States
15                  Brisbane, Australia
16      Abu Dhabi, United Arab Emirates
17                 Melbourne, Australia
18                      Valencia, Spain
19           Seattle, WA, United States
20             Tampa, FL, United States
21                   Gothenburg, Sweden
22                  Adelaide, Australia
23            Edinburgh, United Kingdom
24         San Diego, CA, United States
25          Portland, OR, United States
26                      Munich, Germany
27            Dallas, TX, United States
28              Glasgow, United Kingdom
29                         Muscat, Oman
30                         Oslo, Norway
31                  Canberra, Australia
32           Atlanta, GA, United States
33                     Tallinn, Estonia
34                      Calgary, Canada
35                        Madrid, Spain
36                    Sydney, Australia
37                Auckland, New Zealand
38                        Cork, Ireland
39                     Hamburg, Germany
40                    Stockholm, Sweden
41                      Porto, Portugal
42                  Ljubljana, Slovenia
43       San Antonio, TX, United States
44            Boston, MA, United States
45                 Brno, Czech Republic
46                       Split, Croatia
47                          Doha, Qatar
48          Dubai, United Arab Emirates
49                     Edmonton, Canada
Name: City, dtype: object

In [42]:
data1 = data.copy()

In [43]:
# Function to extract city
def extract_city(location):
    parts = location.split(',')
    city = parts[0].strip()
    if '(' in city:
        city = city.split('(')[0].strip()
    return city

# Function to extract country
def extract_country(location):
    parts = location.split(',')
    country = parts[-1].strip()
    return country

In [44]:
# Extract country from the original 'City' column
data1.insert(2, 'Country', data1['City'].apply(extract_country))

# Extract city from the original 'City' column
data1['City'] = data1['City'].apply(extract_city)

Checking to see if all the values look good

In [45]:
# Display the modified dataframe
data1.head(50)

,Rank,City,Country,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index
0,1,The Hague,Netherlands,223.8,138.9,79.8,80.7,60.2,5.9,21.0,17.5,90.6
1,2,Luxembourg,Luxembourg,220.6,175.9,71.4,76.6,62.0,9.2,27.7,21.6,82.6
2,3,Eindhoven,Netherlands,217.5,139.4,78.1,78.9,62.2,6.0,24.5,19.2,85.4
3,4,Rotterdam,Netherlands,214.2,139.1,71.6,81.2,61.3,5.5,22.9,24.0,87.9
4,5,Zurich,Switzerland,208.1,181.2,77.2,70.3,100.4,12.9,38.1,24.4,81.5
5,6,Copenhagen,Denmark,201.5,123.7,74.3,77.2,75.7,8.2,27.7,21.3,83.7
6,7,Vienna,Austria,197.9,113.1,69.9,79.6,64.3,12.7,22.8,16.3,81.8
7,8,Helsinki,Finland,196.9,111.7,75.5,80.0,66.3,10.8,25.3,12.7,62.8
8,9,Geneva,Switzerland,196.2,152.2,69.3,71.0,101.7,12.0,32.1,25.6,82.6
9,10,Frankfurt,Germany,194.5,142.3,53.9,76.7,63.7,8.2,23.8,32.7,84.7
10,11,Stuttgart,Germany,194.3,145.7,65.5,76.7,64.2,7.5,29.0,38.9,81.1
11,12,Amsterdam,Netherlands,194.1,112.2,71.1,78.3,69.7,11.3,24.2,24.6,87.5
12,13,Reykjavik,Iceland,193.8,104.9,75.8,68.6,83.9,7.3,21.2,15.1,68.8
13,14,Perth,Australia,193.8,140.8,58.3,71.2,69.6,5.5,42.4,27.7,95.7
14,15,Austin,United States,193.3,166.0,58.8,68.8,66.8,3.3,37.2,43.1,82.1
15,16,Brisbane,Australia,193.3,135.2,63.3,74.5,67.9,8.7,40.8,28.5,98.1
16,17,Abu Dhabi,United Arab Emirates,192.4,160.5,88.2,71.1,54.1,5.8,32.9,46.9,43.9
17,18,Melbourne,Australia,192.3,142.8,56.3,73.0,67.8,7.6,41.8,27.5,94.3
18,19,Valencia,Spain,191.7,83.9,69.8,80.3,47.2,7.4,22.8,24.9,93.8
19,20,Seattle,United States,190.8,162.0,46.1,71.5,81.5,5.1,43.4,31.9,91.7
20,21,Tampa,United States,190.5,145.7,54.7,67.8,78.0,2.9,36.2,32.5,84.7
21,22,Gothenburg,Sweden,189.6,125.2,53.6,67.3,60.8,8.3,25.3,19.4,77.5
22,23,Adelaide,Australia,189.4,109.3,67.7,73.9,76.0,7.9,35.5,24.3,95.0
23,24,Edinburgh,United Kingdom,189.0,111.6,68.9,77.5,69.9,7.9,31.0,28.1,84.0
24,25,San Diego,United States,187.6,142.3,59.6,67.9,79.8,6.5,35.2,39.8,97.1
25,26,Portland,United States,186.3,140.2,43.0,71.5,78.4,3.6,33.3,32.4,89.6
26,27,Munich,Germany,186.3,111.7,79.7,77.4,67.8,15.6,30.8,25.0,76.0
27,28,Dallas,United States,186.2,159.1,48.1,66.4,70.5,2.8,35.2,41.9,81.9
28,29,Glasgow,United Kingdom,185.8,121.6,54.9,79.0,65.2,5.1,31.3,34.2,84.8
29,30,Muscat,Oman,185.4,98.1,80.6,64.2,42.8,4.6,19.9,35.1,67.2
30,31,Oslo,Norway,183.1,114.7,66.2,78.0,78.4,10.4,28.1,22.1,60.0
31,32,Canberra,Australia,181.6,104.0,73.6,70.6,79.3,9.5,38.2,24.1,82.7
32,33,Atlanta,United States,181.3,168.1,36.0,67.1,75.7,2.4,41.3,45.0,89.7
33,34,Tallinn,Estonia,180.1,80.3,77.7,74.8,55.3,11.7,24.7,18.8,64.3
34,35,Calgary,Canada,179.8,124.1,61.5,74.1,69.5,4.2,29.0,23.4,33.1
35,36,Madrid,Spain,179.8,92.6,72.8,79.3,53.2,10.6,26.6,36.9,85.5
36,37,Sydney,Australia,179.7,118.5,65.9,74.8,73.4,14.8,43.4,28.6,97.1
37,38,Auckland,New Zealand,179.3,127.8,50.1,69.3,67.7,10.9,38.1,31.7,99.9
38,39,Cork,Ireland,179.2,105.5,64.2,55.8,68.6,6.3,33.9,25.9,89.8
39,40,Hamburg,Germany,178.9,116.7,57.5,74.9,67.4,11.5,33.0,29.1,82.8
40,41,Stockholm,Sweden,177.7,120.3,53.8,66.6,64.7,11.4,34.1,18.5,69.7
41,42,Porto,Portugal,177.3,61.0,67.6,79.4,45.6,11.3,24.5,25.0,96.6
42,43,Ljubljana,Slovenia,176.9,80.2,78.9,67.0,51.5,13.6,26.0,22.5,76.1
43,44,San Antonio,United States,176.6,133.5,52.2,67.9,64.5,5.3,31.7,43.9,80.6
44,45,Boston,United States,176.4,128.3,59.9,72.7,85.8,7.4,44.1,29.8,71.7
45,46,Brno,Czech Republic,175.2,97.6,74.5,76.3,42.8,13.2,26.0,40.8,78.2
46,47,Split,Croatia,174.4,69.0,68.7,71.5,46.0,16.8,18.4,26.6,96.3
47,48,Doha,Qatar,174.3,140.8,83.9,73.4,52.2,5.6,29.2,59.9,36.0
48,49,Dubai,United Arab Emirates,174.1,122.7,83.7,69.7,60.0,4.9,36.3,48.7,50.3
49,50,Edmonton,Canada,173.4,120.9,53.5,77.3,62.5,3.8,28.1,28.8,32.1

# Save clean dataset

In [46]:
data_clean = data1.copy()
data_clean.to_csv('Quality_of_Life_Index_clean.csv', index=False)